<?php

/**
 * Admin Panel - Configuration Management
 *
 * Web-based configuration editor for config.json
 * Features: backup, validation, test mode, JSON format
 */

require_once('session.inc.php');
require_once('config.inc.php');
require_once('csrf.inc.php');

// Check authentication and session timeout
require_authentication(1800, 'index.php');

$success_message = '';
$error_message = '';
$test_results = [];

// Load JSON configuration
$json_config_path = __DIR__ . '/config.json';
$json_config = [];

if (file_exists($json_config_path)) {
    $json_content = file_get_contents($json_config_path);
    $json_config = json_decode($json_content, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        $error_message = 'Failed to parse config.json: ' . json_last_error_msg();
        $json_config = [];
    }
}

// Handle save configuration
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_config'])) {
    if (!csrf_verify()) {
        $error_message = 'CSRF validation failed';
    } else {
        // Create backup
        if (file_exists($json_config_path)) {
            $backup_path = $json_config_path . '.backup.' . date('YmdHis');
            if (copy($json_config_path, $backup_path)) {
                $success_message = "Backup created: " . basename($backup_path) . "<br>";
            } else {
                $error_message = "Failed to create backup file";
            }
        }

        if (!$error_message) {
            // Build JSON configuration
            $new_config = [
                '_comment' => 'Fail2Ban Web Interface Configuration - Generated by admin.php on ' . date('Y-m-d H:i:s'),
                'environment' => $_POST['environment'] ?? 'production',
                'title' => $_POST['title'] ?? 'Fail2Ban Dashboard',
                'server' => [
                    'name' => $_POST['server_name'] ?? 'my-server',
                    'ip' => $_POST['server_ip'] ?? '127.0.0.1'
                ],
                'database' => [
                    'enabled' => isset($_POST['use_central_db']),
                    'host' => $_POST['db_host'] ?? 'localhost',
                    'port' => (int)($_POST['db_port'] ?? 3306),
                    'name' => $_POST['db_database'] ?? 'fail2ban_central',
                    'username' => $_POST['db_username'] ?? 'fail2ban_user',
                    'password' => $_POST['db_password'] ?? '',
                    'charset' => 'utf8mb4'
                ],
                'authentication' => [
                    'users' => []
                ],
                'fail2ban' => [
                    'socket' => $_POST['f2b_socket'] ?? '/var/run/fail2ban/fail2ban.sock',
                    'use_socket_check' => isset($_POST['f2b_use_socket_check']),
                    'usedns' => isset($_POST['f2b_usedns']),
                    'dns_async' => isset($_POST['f2b_dns_async']),
                    'dns_timeout' => (int)($_POST['f2b_dns_timeout'] ?? 2),
                    'dns_cache_ttl' => (int)($_POST['f2b_dns_cache_ttl'] ?? 86400),
                    'noempt' => isset($_POST['f2b_noempt']),
                    'jainfo' => isset($_POST['f2b_jainfo'])
                ],
                'version' => '0.4 (2025)'
            ];

            // Handle authentication user
            $auth_user = [
                'username' => $_POST['auth_user'] ?? 'admin'
            ];

            // If new password provided, hash it
            if (!empty($_POST['auth_password_new'])) {
                $auth_user['password_hash'] = password_hash($_POST['auth_password_new'], PASSWORD_DEFAULT);
                $auth_user['_comment'] = 'Password updated on ' . date('Y-m-d H:i:s');
            } else {
                // Keep existing password_hash if available
                if (isset($json_config['authentication']['users'][0]['password_hash'])) {
                    $auth_user['password_hash'] = $json_config['authentication']['users'][0]['password_hash'];
                } elseif (!empty($_POST['auth_password'])) {
                    // Fallback to plain password if it exists
                    $auth_user['password'] = $_POST['auth_password'];
                }
            }

            $new_config['authentication']['users'][] = $auth_user;

            // Write JSON file
            $json_output = json_encode($new_config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

            if ($json_output === false) {
                $error_message = 'Failed to encode JSON: ' . json_last_error_msg();
            } else {
                if (file_put_contents($json_config_path, $json_output) !== false) {
                    $success_message .= 'Configuration saved successfully to config.json';
                    // Reload configuration
                    $json_config = $new_config;
                } else {
                    $error_message = 'Failed to write config.json. Check file permissions.';
                }
            }
        }
    }
}

// Handle test configuration
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['test_config'])) {
    if (!csrf_verify()) {
        $error_message = 'CSRF validation failed';
    } else {
        $test_results = test_configuration();
    }
}

// Test configuration
function test_configuration()
{
    global $f2b, $config, $db_config;
    $results = [];

    // Test fail2ban connection
    require_once('engine.inc.php');
    $socket_test = check_socket();
    $results['fail2ban'] = [
        'name' => 'Fail2Ban Connection',
        'status' => ($socket_test === 'OK'),
        'message' => $socket_test
    ];

    // Test database connection (if enabled)
    if (isset($config['use_central_db']) && $config['use_central_db'] === true) {
        require_once('db.inc.php');
        try {
            $db = get_db_connection();
            $results['database'] = [
                'name' => 'Database Connection',
                'status' => ($db !== null),
                'message' => $db ? 'Connected successfully' : 'Connection failed'
            ];
        } catch (Exception $e) {
            $results['database'] = [
                'name' => 'Database Connection',
                'status' => false,
                'message' => $e->getMessage()
            ];
        }
    }

    // Test DNS resolution (if enabled)
    if (isset($f2b['usedns']) && $f2b['usedns'] === true) {
        $start = microtime(true);
        $hostname = @gethostbyaddr('8.8.8.8');
        $duration = round((microtime(true) - $start) * 1000, 2);

        $results['dns'] = [
            'name' => 'DNS Resolution',
            'status' => true,
            'message' => "Resolved in {$duration}ms (Result: {$hostname})"
        ];
    }

    // Test cache
    require_once('cache.inc.php');
    $cache_test_key = 'admin_test_' . time();
    cache_set($cache_test_key, 'test_value', 10);
    $cache_result = cache_get($cache_test_key);

    $results['cache'] = [
        'name' => 'Cache System',
        'status' => ($cache_result === 'test_value'),
        'message' => function_exists('apcu_fetch') ? 'Using APCu' : 'Using file cache'
    ];

    return $results;
}

// Helper function to get value from JSON config
function get_json_value($path, $default = '')
{
    global $json_config;
    $keys = explode('.', $path);
    $value = $json_config;

    foreach ($keys as $key) {
        if (!isset($value[$key])) {
            return $default;
        }
        $value = $value[$key];
    }

    return $value;
}
?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel - Fail2Ban</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <style>
        body {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }

        .admin-container {
            max-width: 1200px;
            margin: 2rem auto;
        }

        .card {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
        }

        .form-label {
            font-weight: 600;
            margin-bottom: 0.5rem;
        }

        .section-header {
            background: rgba(255, 255, 255, 0.05);
            padding: 1rem;
            margin: -1rem -1rem 1rem -1rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .test-result {
            padding: 0.5rem;
            margin-bottom: 0.5rem;
            border-radius: 0.375rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .test-result.success {
            background: rgba(25, 135, 84, 0.2);
            border: 1px solid rgba(25, 135, 84, 0.5);
        }

        .test-result.error {
            background: rgba(220, 53, 69, 0.2);
            border: 1px solid rgba(220, 53, 69, 0.5);
        }

        .password-toggle {
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="admin-container">
        <!-- Header -->
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="text-white">
                <i class="bi bi-gear-fill"></i> Admin Panel
            </h1>
            <a href="fail2ban.php" class="btn btn-outline-light">
                <i class="bi bi-arrow-left"></i> Back to Dashboard
            </a>
        </div>

        <!-- Messages -->
        <?php if ($success_message): ?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <i class="bi bi-check-circle-fill"></i> <?php echo $success_message; ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        <?php endif; ?>

        <?php if ($error_message): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <i class="bi bi-exclamation-triangle-fill"></i> <?php echo htmlspecialchars($error_message); ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        <?php endif; ?>

        <!-- Test Results -->
        <?php if (!empty($test_results)): ?>
            <div class="card mb-4">
                <div class="card-header">
                    <h5 class="mb-0"><i class="bi bi-clipboard-check"></i> Configuration Test Results</h5>
                </div>
                <div class="card-body">
                    <?php foreach ($test_results as $test): ?>
                        <div class="test-result <?php echo $test['status'] ? 'success' : 'error'; ?>">
                            <i class="bi bi-<?php echo $test['status'] ? 'check-circle-fill text-success' : 'x-circle-fill text-danger'; ?>"></i>
                            <strong><?php echo htmlspecialchars($test['name']); ?>:</strong>
                            <span><?php echo htmlspecialchars($test['message']); ?></span>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <!-- Configuration Form -->
        <form method="POST" action="">
            <?php echo csrf_token_field(); ?>

            <!-- Environment Settings -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="section-header">
                        <h5 class="mb-0"><i class="bi bi-globe"></i> Environment Settings</h5>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Environment</label>
                            <select class="form-select" name="environment">
                                <option value="development" <?php echo (get_json_value('environment') === 'development') ? 'selected' : ''; ?>>Development</option>
                                <option value="production" <?php echo (get_json_value('environment') === 'production') ? 'selected' : ''; ?>>Production</option>
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Dashboard Title</label>
                            <input type="text" class="form-control" name="title"
                                value="<?php echo htmlspecialchars(get_json_value('title', 'Fail2Ban Dashboard')); ?>">
                        </div>
                    </div>
                </div>
            </div>

            <!-- Server Identification -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="section-header">
                        <h5 class="mb-0"><i class="bi bi-server"></i> Server Identification</h5>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Server Name</label>
                            <input type="text" class="form-control" name="server_name"
                                value="<?php echo htmlspecialchars(get_json_value('server.name', 'my-server')); ?>" required>
                            <small class="text-muted">Unique identifier for this server</small>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Server IP</label>
                            <input type="text" class="form-control" name="server_ip"
                                value="<?php echo htmlspecialchars(get_json_value('server.ip', '127.0.0.1')); ?>" required>
                            <small class="text-muted">IP address of this server</small>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Central Database -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="section-header">
                        <h5 class="mb-0"><i class="bi bi-database"></i> Central Database (Multi-Server)</h5>
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="use_central_db" name="use_central_db"
                                <?php echo get_json_value('database.enabled') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="use_central_db">
                                Enable Central Database
                            </label>
                        </div>
                    </div>
                    <div id="db_settings">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Database Host</label>
                                <input type="text" class="form-control" name="db_host"
                                    value="<?php echo htmlspecialchars(get_json_value('database.host', 'localhost')); ?>">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Database Port</label>
                                <input type="number" class="form-control" name="db_port"
                                    value="<?php echo htmlspecialchars(get_json_value('database.port', '3306')); ?>">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Database Name</label>
                                <input type="text" class="form-control" name="db_database"
                                    value="<?php echo htmlspecialchars(get_json_value('database.name', 'fail2ban_central')); ?>">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="form-label">Database Username</label>
                                <input type="text" class="form-control" name="db_username"
                                    value="<?php echo htmlspecialchars(get_json_value('database.username', 'fail2ban_user')); ?>">
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Database Password</label>
                                <div class="input-group">
                                    <input type="password" class="form-control" name="db_password" id="db_password"
                                        value="<?php echo htmlspecialchars(get_json_value('database.password', '')); ?>">
                                    <button class="btn btn-outline-secondary password-toggle" type="button"
                                        onclick="togglePassword('db_password')">
                                        <i class="bi bi-eye"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Authentication -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="section-header">
                        <h5 class="mb-0"><i class="bi bi-shield-lock"></i> Authentication</h5>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Username</label>
                            <input type="text" class="form-control" name="auth_user"
                                value="<?php
                                        $users = get_json_value('authentication.users', []);
                                        echo htmlspecialchars($users[0]['username'] ?? 'admin');
                                        ?>" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Current Password Hash</label>
                            <input type="text" class="form-control" name="auth_password"
                                value="<?php
                                        $users = get_json_value('authentication.users', []);
                                        echo htmlspecialchars(substr($users[0]['password_hash'] ?? '', 0, 30) . '...');
                                        ?>" readonly>
                            <small class="text-muted">Hashed with bcrypt</small>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">New Password (Optional)</label>
                            <div class="input-group">
                                <input type="password" class="form-control" name="auth_password_new" id="auth_password_new">
                                <button class="btn btn-outline-secondary password-toggle" type="button"
                                    onclick="togglePassword('auth_password_new')">
                                    <i class="bi bi-eye"></i>
                                </button>
                            </div>
                            <small class="text-muted">Will be hashed with bcrypt automatically</small>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Fail2Ban Settings -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="section-header">
                        <h5 class="mb-0"><i class="bi bi-shield-check"></i> Fail2Ban Settings</h5>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Socket Path</label>
                        <input type="text" class="form-control" name="f2b_socket"
                            value="<?php echo htmlspecialchars(get_json_value('fail2ban.socket', '/var/run/fail2ban/fail2ban.sock')); ?>" required>
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="f2b_use_socket_check" name="f2b_use_socket_check"
                                <?php echo get_json_value('fail2ban.use_socket_check') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="f2b_use_socket_check">
                                Use Socket File Check (disable if using fail2ban-client directly)
                            </label>
                        </div>
                    </div>

                    <hr class="my-4">
                    <h6 class="mb-3"><i class="bi bi-globe"></i> DNS & Hostname Settings</h6>

                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="f2b_usedns" name="f2b_usedns"
                                <?php echo get_json_value('fail2ban.usedns') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="f2b_usedns">
                                Enable Hostname Resolution
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="f2b_dns_async" name="f2b_dns_async"
                                <?php echo get_json_value('fail2ban.dns_async') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="f2b_dns_async">
                                Asynchronous DNS Loading (Recommended for performance)
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">DNS Timeout (seconds)</label>
                            <input type="number" class="form-control" name="f2b_dns_timeout"
                                value="<?php echo htmlspecialchars(get_json_value('fail2ban.dns_timeout', '2')); ?>" min="1" max="30">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">DNS Cache TTL (seconds)</label>
                            <input type="number" class="form-control" name="f2b_dns_cache_ttl"
                                value="<?php echo htmlspecialchars(get_json_value('fail2ban.dns_cache_ttl', '86400')); ?>" min="60">
                            <small class="text-muted">86400 = 24 hours</small>
                        </div>
                    </div>

                    <hr class="my-4">
                    <h6 class="mb-3"><i class="bi bi-eye"></i> Display Settings</h6>

                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="f2b_noempt" name="f2b_noempt"
                                <?php echo get_json_value('fail2ban.noempt') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="f2b_noempt">
                                Hide Empty Jails
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="f2b_jainfo" name="f2b_jainfo"
                                <?php echo get_json_value('fail2ban.jainfo') ? 'checked' : ''; ?>>
                            <label class="form-check-label" for="f2b_jainfo">
                                Show Jail Information (findtime, bantime, maxretry)
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Action Buttons -->
            <div class="card">
                <div class="card-body">
                    <div class="d-flex gap-2 justify-content-end">
                        <button type="submit" name="test_config" class="btn btn-info">
                            <i class="bi bi-clipboard-check"></i> Test Configuration
                        </button>
                        <button type="submit" name="save_config" class="btn btn-success">
                            <i class="bi bi-save"></i> Save Configuration
                        </button>
                    </div>
                    <small class="text-muted d-block mt-2">
                        <i class="bi bi-info-circle"></i> Configuration will be saved to config.json. A backup will be created automatically.
                    </small>
                </div>
            </div>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Toggle password visibility
        function togglePassword(fieldId) {
            const field = document.getElementById(fieldId);
            const icon = event.currentTarget.querySelector('i');

            if (field.type === 'password') {
                field.type = 'text';
                icon.classList.remove('bi-eye');
                icon.classList.add('bi-eye-slash');
            } else {
                field.type = 'password';
                icon.classList.remove('bi-eye-slash');
                icon.classList.add('bi-eye');
            }
        }

        // Toggle database settings visibility
        document.getElementById('use_central_db').addEventListener('change', function() {
            const dbSettings = document.getElementById('db_settings');
            dbSettings.style.display = this.checked ? 'block' : 'none';
        });

        // Initial state
        document.addEventListener('DOMContentLoaded', function() {
            const useCentralDb = document.getElementById('use_central_db');
            const dbSettings = document.getElementById('db_settings');
            dbSettings.style.display = useCentralDb.checked ? 'block' : 'none';
        });
    </script>
</body>

</html>